FILE=proj5
LOGIN=xherma34

all:
	pdflatex $(FILE).tex

zip:
	zip $(LOGIN)-fit.zip *.tex 2darraz.png arraytypes.png C-Arrays.jpg *.pdf Makefile

clean:
	rm -rf *.dvi *.out *.aux *.log *.ps *.pdf *.zip *.toc *.snm *.nav
